services:
  bot:
    type: web
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    environment:
      API_ID: "35981014"
      API_HASH: "4e788ed1a686308838891734a4173c48"
      BOT_TOKEN: "8735415736:AAE72qIhErgje2egt2_1DSlpOszhDCootXY"
